### PR TITLE
added NumpyDataset tutorial link to website

### PR DESCRIPTION
**Pull request by pvskand**
Added the link of [NumpyDataset Tutorial](https://github.com/deepchem/deepchem/pull/1116) in the website's notebook examples webpage.

### CODE REVIEW

**Comment by pvskand** [comment]
@rbharath, Is this fine?

**Comment by lilleswing** [comment]
The tutorial file wasn't created an in the repo yet.  I did this [here](https://github.com/deepchem/deepchem.io/pull/5)  One has to build the docs calling 
```python
cd examples/notebooks
python ../../devtools/jenkins/convert_to_rst.py
cd ../..

sphinx-apidoc -f -o docs/source deepchem
sphinx-build -b html docs/source docs/_build
```
This will generate the HTML file for the tutorial.  We have to change the headers on the file also as the headers have changed because we now support multiple stable versions of docs.

All in All not the simplest process and it could use some automation.

**Comment by lilleswing** [comment]
LGTM

**Comment by pvskand** [comment]
@lilleswing, the tutorial still doesn't seem to come up on the [website](https://deepchem.io/docs/notebooks/index.html). But the tutorial html is up at [https://deepchem.io/docs/notebooks/Deepchem_NumpyDataset_tutorial.html](https://deepchem.io/docs/notebooks/Deepchem_NumpyDataset_tutorial.html). The color schema of the tutorial webpage seems to be disturbed. Any reason for that?

**Comment by lilleswing** [comment]
Yeah I'm seeing it -- the color scheme was busted HTML due to not closing a div.  Everything else... not sure what is happening and I am looking into it.

**Comment by pvskand** [comment]
@lilleswing, it's fixed now. Did you get what the problem was? or was it that github took time to update the web pages?

**Comment by lilleswing** [comment]
We have a CDN in front of the static website so it takes 24 hours to bust through the cache.  So everything that gets uploaded will have a 24 hour delay.

**Comment by pvskand** [comment]
Aah. Okay.

**Pull request merged**
